name: "Update data/*.json"
on:
  schedule:
    - cron: "5 0 * * *"
  workflow_dispatch:

jobs:
  update-data:
    name: Get octoprint.org data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.4.0
        name: Checkout repo
        with:
          ref: 'pages'
          
      - name: Run script
        run: |
          git branch
          git pull
          git merge origin/main
          ./build.sh
          git commit -m "Updating pages"
          git push
